In [78]:
#import libraries
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

# Load Dataset

In [79]:
df = pd.read_csv("rumah123_data_single_raw_concated.csv")
df

Unnamed: 0                                              Judul  \
0              0  RUMAH 2 LANTAI TENGAH KOTA PERUMAHAN BUKIT DAM...   
1              0       BALIKPAPAN,  RUMAH CANTIK TENGAH KOTA (Y255)   
2              1  Rumah Luas Lokasi Strategis di Gunung Samarind...   
3              1   DUA RUMAH BERSEBELAHAN SATU SERTIFIKAT SIAP HUNI   
4              2  Rumah Minimalis Baru Renovasi Untuk Keluarga M...   
...          ...                                                ...   
1408        1462             Rumah Murah Harga Nego Dalam Perumahan   
1409        1463                        Perumahan Elit Pupuk Kaltim   
1410        1464                  Rumah Baru Minimalis Kpr Tanpa Dp   
1411        1465                             BALIKPAPAN POKA (Y140)   
1412        1466                            Rumah cantik tanah luas   

              Harga                          Lokasi  Kamar Tidur  Kamar Mandi  \
0     Rp 1,5 Miliar  Balikpapan Selatan, Balikpapan          5.0          3.0   
1     Rp 1,6 Miliar  Balikpapan Selatan, Balikpapan          3.0          2.0   
2     Rp 3,1 Miliar    Balikpapan Utara, Balikpapan          3.0          2.0   
3     Rp 1,5 Miliar  Balikpapan Selatan, Balikpapan          5.0          4.0   
4       Rp 600 Juta    Balikpapan Utara, Balikpapan          2.0          2.0   
...             ...                             ...          ...          ...   
1408    Rp 150 Juta    Balikpapan Timur, Balikpapan          2.0          1.0   
1409  Rp 2,7 Miliar  Balikpapan Selatan, Balikpapan          3.0          3.0   
1410    Rp 395 Juta    Balikpapan Utara, Balikpapan          2.0          1.0   
1411  Rp 2,1 Miliar           Sepinggan, Balikpapan          5.0          2.0   
1412  Rp 2,5 Miliar  Balikpapan Selatan, Balikpapan          3.0          3.0   

     Luas Tanah Luas Bangunan  Carport Tipe Properti  ... Ruang Tamu  \
0        144 m²        207 m²      1.0         Rumah  ...      Tidak   
1        210 m²        176 m²      NaN         Rumah  ...        NaN   
2        534 m²        200 m²      3.0         Rumah  ...         Ya   
3        193 m²        150 m²      NaN         Rumah  ...        NaN   
4         80 m²        140 m²      1.0         Rumah  ...         Ya   
...         ...           ...      ...           ...  ...        ...   
1408     120 m²         36 m²      NaN         Rumah  ...      Tidak   
1409     374 m²        200 m²      NaN         Rumah  ...        NaN   
1410      72 m²         45 m²      1.0         Rumah  ...         Ya   
1411     403 m²        200 m²      NaN         Rumah  ...        NaN   
1412     600 m²        200 m²      NaN         Rumah  ...        NaN   

     Kondisi Perabotan  Jumlah Lantai      Pemandangan Terjangkau Internet  \
0       Semi Furnished            2.0  Pemukiman Warga                  Ya   
1       Semi Furnished            NaN              NaN                 NaN   
2                  NaN            1.0              NaN                  Ya   
3                  NaN            NaN              NaN                 NaN   
4       Semi Furnished            1.0              NaN                  Ya   
...                ...            ...              ...                 ...   
1408       Unfurnished            1.0  Pemukiman Warga                  Ya   
1409               NaN            NaN              NaN                 NaN   
1410       Unfurnished            1.0  Pemukiman Warga                  Ya   
1411               NaN            NaN              NaN                 NaN   
1412       Unfurnished            1.0              NaN                 NaN   

     Lebar Jalan     Sumber Air   Hook Kondisi Properti Tipe Iklan  
0        2 Mobil  PAM atau PDAM  Tidak            Bagus     Dijual  
1            NaN            NaN    NaN            Bagus     Dijual  
2            NaN  PAM atau PDAM  Tidak            Bagus     Dijual  
3            NaN            NaN    NaN              NaN     Dijual  
4            NaN  PAM atau PDAM  

# Check column

In [80]:
df.columns

Index(['Unnamed: 0', 'Judul', 'Harga', 'Lokasi', 'Kamar Tidur', 'Kamar Mandi',
       'Luas Tanah', 'Luas Bangunan', 'Carport', 'Tipe Properti', 'Sertifikat',
       'Daya Listrik', 'Kamar Pembantu', 'Dapur', 'Ruang Makan', 'Ruang Tamu',
       'Kondisi Perabotan', 'Jumlah Lantai', 'Pemandangan',
       'Terjangkau Internet', 'Lebar Jalan', 'Sumber Air', 'Hook',
       'Kondisi Properti', 'Tipe Iklan'],
      dtype='object')

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413 entries, 0 to 1412
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Unnamed: 0           1413 non-null   int64  
 1   Judul                1413 non-null   object 
 2   Harga                1413 non-null   object 
 3   Lokasi               1413 non-null   object 
 4   Kamar Tidur          1362 non-null   float64
 5   Kamar Mandi          1361 non-null   float64
 6   Luas Tanah           1413 non-null   object 
 7   Luas Bangunan        1413 non-null   object 
 8   Carport              253 non-null    float64
 9   Tipe Properti        1413 non-null   object 
 10  Sertifikat           1412 non-null   object 
 11  Daya Listrik         1362 non-null   object 
 12  Kamar Pembantu       242 non-null    float64
 13  Dapur                228 non-null    float64
 14  Ruang Makan          696 non-null    object 
 15  Ruang Tamu           698 non-null    o

# Rename column name

In [85]:
df.rename(columns = {'Kamar Tidur' : 'Kamar_Tidur', 'Kamar Mandi' : 'Kamar_Mandi' , 'Luas Tanah' : 'Luas_Tanah',
                    'Luas Bangunan' : 'Luas_Bangunan', 'Tipe Properti'  : 'Tipe_Properti', 'Daya Listrik' : 'Daya_Listrik', 'Kamar Pembantu' : 'Kamar_Pembantu',
                    'Ruang Makan' : 'Ruang_Makan', 'Ruang Tamu' : 'Ruang_Tamu', 'Kondisi Perabotan' : 'Kondisi_Perabotan', 'Jumlah Lantai' : 'Jumlah_Lantai', 'Terjangkau Internet' : 'Terjangkau_Internet',
                    'Lebar Jalan' : 'Lebar_Jalan', 'Sumber Air' : 'Sumber_Air', 'Kondisi Properti' : 'Kondisi_Properti', 'Tipe Iklan' : 'Tipe_Iklan'}, inplace=True)
df

Unnamed: 0                                              Judul  \
0              0  RUMAH 2 LANTAI TENGAH KOTA PERUMAHAN BUKIT DAM...   
1              0       BALIKPAPAN,  RUMAH CANTIK TENGAH KOTA (Y255)   
2              1  Rumah Luas Lokasi Strategis di Gunung Samarind...   
3              1   DUA RUMAH BERSEBELAHAN SATU SERTIFIKAT SIAP HUNI   
4              2  Rumah Minimalis Baru Renovasi Untuk Keluarga M...   
...          ...                                                ...   
1408        1462             Rumah Murah Harga Nego Dalam Perumahan   
1409        1463                        Perumahan Elit Pupuk Kaltim   
1410        1464                  Rumah Baru Minimalis Kpr Tanpa Dp   
1411        1465                             BALIKPAPAN POKA (Y140)   
1412        1466                            Rumah cantik tanah luas   

              Harga                          Lokasi  Kamar_Tidur  Kamar_Mandi  \
0     Rp 1,5 Miliar  Balikpapan Selatan, Balikpapan          5.0          3.0   
1     Rp 1,6 Miliar  Balikpapan Selatan, Balikpapan          3.0          2.0   
2     Rp 3,1 Miliar    Balikpapan Utara, Balikpapan          3.0          2.0   
3     Rp 1,5 Miliar  Balikpapan Selatan, Balikpapan          5.0          4.0   
4       Rp 600 Juta    Balikpapan Utara, Balikpapan          2.0          2.0   
...             ...                             ...          ...          ...   
1408    Rp 150 Juta    Balikpapan Timur, Balikpapan          2.0          1.0   
1409  Rp 2,7 Miliar  Balikpapan Selatan, Balikpapan          3.0          3.0   
1410    Rp 395 Juta    Balikpapan Utara, Balikpapan          2.0          1.0   
1411  Rp 2,1 Miliar           Sepinggan, Balikpapan          5.0          2.0   
1412  Rp 2,5 Miliar  Balikpapan Selatan, Balikpapan          3.0          3.0   

     Luas_Tanah Luas_Bangunan  Carport Tipe_Properti  ... Ruang_Tamu  \
0        144 m²        207 m²      1.0         Rumah  ...      Tidak   
1        210 m²        176 m²      NaN         Rumah  ...        NaN   
2        534 m²        200 m²      3.0         Rumah  ...         Ya   
3        193 m²        150 m²      NaN         Rumah  ...        NaN   
4         80 m²        140 m²      1.0         Rumah  ...         Ya   
...         ...           ...      ...           ...  ...        ...   
1408     120 m²         36 m²      NaN         Rumah  ...      Tidak   
1409     374 m²        200 m²      NaN         Rumah  ...        NaN   
1410      72 m²         45 m²      1.0         Rumah  ...         Ya   
1411     403 m²        200 m²      NaN         Rumah  ...        NaN   
1412     600 m²        200 m²      NaN         Rumah  ...        NaN   

     Kondisi_Perabotan  Jumlah_Lantai      Pemandangan Terjangkau_Internet  \
0       Semi Furnished            2.0  Pemukiman Warga                  Ya   
1       Semi Furnished            NaN              NaN                 NaN   
2                  NaN            1.0              NaN                  Ya   
3                  NaN            NaN              NaN                 NaN   
4       Semi Furnished            1.0              NaN                  Ya   
...                ...            ...              ...                 ...   
1408       Unfurnished            1.0  Pemukiman Warga                  Ya   
1409               NaN            NaN              NaN                 NaN   
1410       Unfurnished            1.0  Pemukiman Warga                  Ya   
1411               NaN            NaN              NaN                 NaN   
1412       Unfurnished            1.0              NaN                 NaN   

     Lebar_Jalan     Sumber_Air   Hook Kondisi_Properti Tipe_Iklan  
0        2 Mobil  PAM atau PDAM  Tidak            Bagus     Dijual  
1            NaN            NaN    NaN            Bagus     Dijual  
2            NaN  PAM atau PDAM  Tidak            Bagus     Dijual  
3            NaN            NaN    NaN              NaN     Dijual  
4            NaN  PAM atau PDAM  

# Check missing value

In [86]:
df.isna().sum()

Unnamed: 0                0
Judul                     0
Harga                     0
Lokasi                    0
Kamar_Tidur              51
Kamar_Mandi              52
Luas_Tanah                0
Luas_Bangunan             0
Carport                1160
Tipe_Properti             0
Sertifikat                1
Daya_Listrik             51
Kamar_Pembantu         1171
Dapur                  1185
Ruang_Makan             717
Ruang_Tamu              715
Kondisi_Perabotan      1029
Jumlah_Lantai          1013
Pemandangan            1081
Terjangkau_Internet     716
Lebar_Jalan            1093
Sumber_Air             1082
Hook                    716
Kondisi_Properti        918
Tipe_Iklan                0
dtype: int64

In [87]:
df['Kamar_Tidur'].unique()

array([ 5.,  3.,  2., nan,  4., 32.,  6.,  7., 12., 10., 42.,  8., 15.,
        9.,  1., 11., 28., 24., 29., 17., 13., 14., 99., 25.])

In [88]:
df['Kamar_Mandi'].unique()

array([  3.,   2.,   4.,   1.,  nan,   5.,   6.,  10.,  45.,  15.,   9.,
         7.,   8.,  13.,  29.,  11., 120.,  12.,  14.,  99.,  25.])

In [89]:
df['Carport'].unique()

array([ 1., nan,  3.,  2.,  5.,  4., 10.,  6.])

In [90]:
df['Sertifikat'].unique()

array(['SHM - Sertifikat Hak Milik', 'HGB - Hak Guna Bangunan',
       'Lainnya (PPJB,Girik,Adat,dll)', nan], dtype=object)

In [91]:
df['Daya_Listrik'].unique()

array(['4400 Watt', '3500 Watt', '2200 Watt', '1300 Watt', '10000 Watt',
       nan, '16500 Watt', '5500 Watt', '23000 Watt', '7700 Watt',
       '33000 Watt', '900 Watt', '6600 Watt', '7600 Watt', '13300 Watt',
       '13200 Watt', '3300 Watt', '12700 Watt', '10600 Watt',
       '22000 Watt', '13900 Watt', '9500 Watt', '11000 Watt',
       '19000 Watt'], dtype=object)

In [92]:
df['Kamar_Pembantu'].unique()

array([ 1., nan,  3.,  2.,  5., 19.,  4.])

In [93]:
df['Dapur'].unique()

array([ 1., nan,  2., 10.])

In [94]:
df['Ruang_Makan'].unique()

array(['Tidak', nan, 'Ya'], dtype=object)

In [95]:
df['Ruang_Tamu'].unique()

array(['Tidak', nan, 'Ya'], dtype=object)

In [96]:
df['Kondisi_Perabotan'].unique()

array(['Semi Furnished', nan, 'Unfurnished', 'Furnished'], dtype=object)

In [97]:
df['Jumlah_Lantai'].unique()

array([ 2., nan,  1.,  3.,  5.,  4., 19.])

In [98]:
df['Pemandangan'].unique()

array(['Pemukiman Warga', nan, 'Taman Kota', 'Pantai', 'Perkotaan',
       'Pegunungan', 'Pedesaan'], dtype=object)

In [99]:
df['Terjangkau_Internet'].unique()

array(['Ya', nan, 'Tidak'], dtype=object)

In [100]:
df['Lebar_Jalan'].unique()

array(['2 Mobil', nan, '4 Mobil', '3 Mobil', '1 Mobil'], dtype=object)

In [101]:
df['Sumber_Air'].unique()

array(['PAM atau PDAM', nan, 'Sumur Bor', 'Sumur Galian', 'Sumur Pompa'],
      dtype=object)

In [102]:
df['Hook'].unique()

array(['Tidak', nan, 'Ya'], dtype=object)

In [103]:
df['Kondisi_Properti'].unique()

array(['Bagus', nan, 'Butuh Renovasi', 'Baru', 'Bagus Sekali',
       'Sudah Renovasi'], dtype=object)

# Fill the missing value

In [104]:
#for object column

fill_value = "Tidak ada keterangan"

df['Sertifikat'] = df['Sertifikat'].fillna(fill_value)
df['Daya_Listrik'] = df['Daya_Listrik'].fillna(fill_value)
df['Ruang_Makan'] = df['Ruang_Makan'].fillna(fill_value)
df['Ruang_Tamu'] = df['Ruang_Tamu'].fillna(fill_value)
df['Kondisi_Perabotan'] = df['Kondisi_Perabotan'].fillna(fill_value)
df['Pemandangan'] = df['Pemandangan'].fillna(fill_value)
df['Terjangkau_Internet'] = df['Terjangkau_Internet'].fillna(fill_value)
df['Lebar_Jalan'] = df['Lebar_Jalan'].fillna(fill_value)
df['Sumber_Air'] = df['Sumber_Air'].fillna(fill_value)
df['Hook'] = df['Hook'].fillna(fill_value)
df['Kondisi_Properti'] = df['Kondisi_Properti'].fillna(fill_value)


In [105]:
#for numeric column

fill_value = 0

df['Kamar_Tidur'] = df['Kamar_Tidur'].fillna(fill_value)
df['Kamar_Mandi'] = df['Kamar_Mandi'].fillna(fill_value)
df['Carport'] = df['Carport'].fillna(fill_value)
df['Kamar_Pembantu'] = df['Kamar_Pembantu'].fillna(fill_value)
df['Dapur'] = df['Dapur'].fillna(fill_value)
df['Jumlah_Lantai'] = df['Jumlah_Lantai'].fillna(fill_value)


In [106]:
df.isna().sum()

Unnamed: 0             0
Judul                  0
Harga                  0
Lokasi                 0
Kamar_Tidur            0
Kamar_Mandi            0
Luas_Tanah             0
Luas_Bangunan          0
Carport                0
Tipe_Properti          0
Sertifikat             0
Daya_Listrik           0
Kamar_Pembantu         0
Dapur                  0
Ruang_Makan            0
Ruang_Tamu             0
Kondisi_Perabotan      0
Jumlah_Lantai          0
Pemandangan            0
Terjangkau_Internet    0
Lebar_Jalan            0
Sumber_Air             0
Hook                   0
Kondisi_Properti       0
Tipe_Iklan             0
dtype: int64

In [107]:
df

Unnamed: 0                                              Judul  \
0              0  RUMAH 2 LANTAI TENGAH KOTA PERUMAHAN BUKIT DAM...   
1              0       BALIKPAPAN,  RUMAH CANTIK TENGAH KOTA (Y255)   
2              1  Rumah Luas Lokasi Strategis di Gunung Samarind...   
3              1   DUA RUMAH BERSEBELAHAN SATU SERTIFIKAT SIAP HUNI   
4              2  Rumah Minimalis Baru Renovasi Untuk Keluarga M...   
...          ...                                                ...   
1408        1462             Rumah Murah Harga Nego Dalam Perumahan   
1409        1463                        Perumahan Elit Pupuk Kaltim   
1410        1464                  Rumah Baru Minimalis Kpr Tanpa Dp   
1411        1465                             BALIKPAPAN POKA (Y140)   
1412        1466                            Rumah cantik tanah luas   

              Harga                          Lokasi  Kamar_Tidur  Kamar_Mandi  \
0     Rp 1,5 Miliar  Balikpapan Selatan, Balikpapan          5.0          3.0   
1     Rp 1,6 Miliar  Balikpapan Selatan, Balikpapan          3.0          2.0   
2     Rp 3,1 Miliar    Balikpapan Utara, Balikpapan          3.0          2.0   
3     Rp 1,5 Miliar  Balikpapan Selatan, Balikpapan          5.0          4.0   
4       Rp 600 Juta    Balikpapan Utara, Balikpapan          2.0          2.0   
...             ...                             ...          ...          ...   
1408    Rp 150 Juta    Balikpapan Timur, Balikpapan          2.0          1.0   
1409  Rp 2,7 Miliar  Balikpapan Selatan, Balikpapan          3.0          3.0   
1410    Rp 395 Juta    Balikpapan Utara, Balikpapan          2.0          1.0   
1411  Rp 2,1 Miliar           Sepinggan, Balikpapan          5.0          2.0   
1412  Rp 2,5 Miliar  Balikpapan Selatan, Balikpapan          3.0          3.0   

     Luas_Tanah Luas_Bangunan  Carport Tipe_Properti  ...  \
0        144 m²        207 m²      1.0         Rumah  ...   
1        210 m²        176 m²      0.0         Rumah  ...   
2        534 m²        200 m²      3.0         Rumah  ...   
3        193 m²        150 m²      0.0         Rumah  ...   
4         80 m²        140 m²      1.0         Rumah  ...   
...         ...           ...      ...           ...  ...   
1408     120 m²         36 m²      0.0         Rumah  ...   
1409     374 m²        200 m²      0.0         Rumah  ...   
1410      72 m²         45 m²      1.0         Rumah  ...   
1411     403 m²        200 m²      0.0         Rumah  ...   
1412     600 m²        200 m²      0.0         Rumah  ...   

                Ruang_Tamu     Kondisi_Perabotan  Jumlah_Lantai  \
0                    Tidak        Semi Furnished            2.0   
1     Tidak ada keterangan        Semi Furnished            0.0   
2                       Ya  Tidak ada keterangan            1.0   
3     Tidak ada keterangan  Tidak ada keterangan            0.0   
4                       Ya        Semi Furnished            1.0   
...                    ...                   ...            ...   
1408                 Tidak           Unfurnished            1.0   
1409  Tidak ada keterangan  Tidak ada keterangan            0.0   
1410                    Ya           Unfurnished            1.0   
1411  Tidak ada keterangan  Tidak ada keterangan            0.0   
1412  Tidak ada keterangan           Unfurnished            1.0   

               Pemandangan   Terjangkau_Internet           Lebar_Jalan  \
0          Pemukiman Warga                    Ya               2 Mobil   
1     Tidak ada keterangan  Tidak ada keterangan  Tidak ada keterangan   
2     Tidak ada keterangan                    Ya  Tidak ada keterangan   
3     Tidak ada keterangan  Tidak ada keterangan  Tidak ada keterangan   
4     Tidak ada keterangan                    Ya  Tidak ada keterangan   
...                    ...                   ...                   ...   
1408       Pemukiman Warga                    Ya  Tidak ada keterangan   
1409  Tidak ada keterangan  Tidak ada keterangan  