In [4]:
#import libraries
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

In [5]:
df = pd.read_csv("data_final_raw.csv")
df

Unnamed: 0                                              Judul  \
0              0  RUMAH 2 LANTAI TENGAH KOTA PERUMAHAN BUKIT DAM...   
1              1  Rumah Luas Lokasi Strategis di Gunung Samarind...   
2              2  Rumah Minimalis Baru Renovasi Untuk Keluarga M...   
3              3  DIJUAL CEPAT RUMAH DI JALAN SWADAYA, KARANG RE...   
4              4       Rumah Minimalis Modern Smart Home Tanah Luas   
...          ...                                                ...   
1421        1462             Rumah Murah Harga Nego Dalam Perumahan   
1422        1463                        Perumahan Elit Pupuk Kaltim   
1423        1464                  Rumah Baru Minimalis Kpr Tanpa Dp   
1424        1465                             BALIKPAPAN POKA (Y140)   
1425        1466                            Rumah cantik tanah luas   

              Harga                          Lokasi  Kamar Tidur  Kamar Mandi  \
0     Rp 1,5 Miliar  Balikpapan Selatan, Balikpapan          5.0          3.0   
1     Rp 3,1 Miliar    Balikpapan Utara, Balikpapan          3.0          2.0   
2       Rp 600 Juta    Balikpapan Utara, Balikpapan          2.0          2.0   
3       Rp 510 Juta   Balikpapan Tengah, Balikpapan          3.0          2.0   
4       Rp 850 Juta    Balikpapan Utara, Balikpapan          3.0          3.0   
...             ...                             ...          ...          ...   
1421    Rp 150 Juta    Balikpapan Timur, Balikpapan          2.0          1.0   
1422  Rp 2,7 Miliar  Balikpapan Selatan, Balikpapan          3.0          3.0   
1423    Rp 395 Juta    Balikpapan Utara, Balikpapan          2.0          1.0   
1424  Rp 2,1 Miliar           Sepinggan, Balikpapan          5.0          2.0   
1425  Rp 2,5 Miliar  Balikpapan Selatan, Balikpapan          3.0          3.0   

     Luas Tanah Luas Bangunan  Carport Tipe Properti  ... Ruang Tamu  \
0        144 m²        207 m²      1.0         Rumah  ...      Tidak   
1        534 m²        200 m²      3.0         Rumah  ...         Ya   
2         80 m²        140 m²      1.0         Rumah  ...         Ya   
3        201 m²        150 m²      NaN         Rumah  ...      Tidak   
4        120 m²         65 m²      1.0         Rumah  ...         Ya   
...         ...           ...      ...           ...  ...        ...   
1421     120 m²         36 m²      NaN         Rumah  ...      Tidak   
1422     374 m²        200 m²      NaN         Rumah  ...        NaN   
1423      72 m²         45 m²      1.0         Rumah  ...         Ya   
1424     403 m²        200 m²      NaN         Rumah  ...        NaN   
1425     600 m²        200 m²      NaN         Rumah  ...        NaN   

     Kondisi Perabotan  Jumlah Lantai      Pemandangan Terjangkau Internet  \
0       Semi Furnished            2.0  Pemukiman Warga                  Ya   
1                  NaN            1.0              NaN                  Ya   
2       Semi Furnished            1.0              NaN                  Ya   
3          Unfurnished            1.0              NaN               Tidak   
4          Unfurnished            2.0  Pemukiman Warga                  Ya   
...                ...            ...              ...                 ...   
1421       Unfurnished            1.0  Pemukiman Warga                  Ya   
1422               NaN            NaN              NaN                 NaN   
1423       Unfurnished            1.0  Pemukiman Warga                  Ya   
1424               NaN            NaN              NaN                 NaN   
1425       Unfurnished            1.0              NaN                 NaN   

     Lebar Jalan     Sumber Air   Hook Kondisi Properti Tipe Iklan  
0        2 Mobil  PAM atau PDAM  Tidak            Bagus     Dijual  
1            NaN  PAM atau PDAM  Tidak            Bagus     Dijual  
2            NaN  PAM atau PDAM  Tidak            Bagus     Dijual  
3            NaN            NaN  Tidak            Bagus     Dijual  
4            NaN      Sumur Bor  

In [7]:
df.columns

Index(['Unnamed: 0', 'Judul', 'Harga', 'Lokasi', 'Kamar Tidur', 'Kamar Mandi',
       'Luas Tanah', 'Luas Bangunan', 'Carport', 'Tipe Properti', 'Sertifikat',
       'Daya Listrik', 'Kamar Pembantu', 'Dapur', 'Ruang Makan', 'Ruang Tamu',
       'Kondisi Perabotan', 'Jumlah Lantai', 'Pemandangan',
       'Terjangkau Internet', 'Lebar Jalan', 'Sumber Air', 'Hook',
       'Kondisi Properti', 'Tipe Iklan'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Unnamed: 0           1426 non-null   int64  
 1   Judul                1426 non-null   object 
 2   Harga                1426 non-null   object 
 3   Lokasi               1426 non-null   object 
 4   Kamar Tidur          1375 non-null   float64
 5   Kamar Mandi          1374 non-null   float64
 6   Luas Tanah           1426 non-null   object 
 7   Luas Bangunan        1426 non-null   object 
 8   Carport              257 non-null    float64
 9   Tipe Properti        1426 non-null   object 
 10  Sertifikat           1425 non-null   object 
 11  Daya Listrik         1375 non-null   object 
 12  Kamar Pembantu       242 non-null    float64
 13  Dapur                231 non-null    float64
 14  Ruang Makan          705 non-null    object 
 15  Ruang Tamu           707 non-null    o

In [10]:
df.rename(columns = {'Kamar Tidur' : 'Kamar_Tidur', 'Kamar Mandi' : 'Kamar_Mandi' , 'Luas Tanah' : 'Luas_Tanah',
                    'Luas Bangunan' : 'Luas_Bangunan', 'Tipe Properti'  : 'Tipe_Properti', 'Daya Listrik' : 'Daya_Listrik', 'Kamar Pembantu' : 'Kamar_Pembantu',
                    'Ruang Makan' : 'Ruang_Makan', 'Ruang Tamu' : 'Ruang_Tamu', 'Kondisi Perabotan' : 'Kondisi_Perabotan', 'Jumlah Lantai' : 'Jumlah_Lantai', 'Terjangkau Internet' : 'Terjangkau_Internet'}, inplace=True)
df

Unnamed: 0                                              Judul  \
0              0  RUMAH 2 LANTAI TENGAH KOTA PERUMAHAN BUKIT DAM...   
1              1  Rumah Luas Lokasi Strategis di Gunung Samarind...   
2              2  Rumah Minimalis Baru Renovasi Untuk Keluarga M...   
3              3  DIJUAL CEPAT RUMAH DI JALAN SWADAYA, KARANG RE...   
4              4       Rumah Minimalis Modern Smart Home Tanah Luas   
...          ...                                                ...   
1421        1462             Rumah Murah Harga Nego Dalam Perumahan   
1422        1463                        Perumahan Elit Pupuk Kaltim   
1423        1464                  Rumah Baru Minimalis Kpr Tanpa Dp   
1424        1465                             BALIKPAPAN POKA (Y140)   
1425        1466                            Rumah cantik tanah luas   

              Harga                          Lokasi  Kamar_Tidur  Kamar_Mandi  \
0     Rp 1,5 Miliar  Balikpapan Selatan, Balikpapan          5.0          3.0   
1     Rp 3,1 Miliar    Balikpapan Utara, Balikpapan          3.0          2.0   
2       Rp 600 Juta    Balikpapan Utara, Balikpapan          2.0          2.0   
3       Rp 510 Juta   Balikpapan Tengah, Balikpapan          3.0          2.0   
4       Rp 850 Juta    Balikpapan Utara, Balikpapan          3.0          3.0   
...             ...                             ...          ...          ...   
1421    Rp 150 Juta    Balikpapan Timur, Balikpapan          2.0          1.0   
1422  Rp 2,7 Miliar  Balikpapan Selatan, Balikpapan          3.0          3.0   
1423    Rp 395 Juta    Balikpapan Utara, Balikpapan          2.0          1.0   
1424  Rp 2,1 Miliar           Sepinggan, Balikpapan          5.0          2.0   
1425  Rp 2,5 Miliar  Balikpapan Selatan, Balikpapan          3.0          3.0   

     Luas_Tanah Luas_Bangunan  Carport Tipe_Properti  ... Ruang_Tamu  \
0        144 m²        207 m²      1.0         Rumah  ...      Tidak   
1        534 m²        200 m²      3.0         Rumah  ...         Ya   
2         80 m²        140 m²      1.0         Rumah  ...         Ya   
3        201 m²        150 m²      NaN         Rumah  ...      Tidak   
4        120 m²         65 m²      1.0         Rumah  ...         Ya   
...         ...           ...      ...           ...  ...        ...   
1421     120 m²         36 m²      NaN         Rumah  ...      Tidak   
1422     374 m²        200 m²      NaN         Rumah  ...        NaN   
1423      72 m²         45 m²      1.0         Rumah  ...         Ya   
1424     403 m²        200 m²      NaN         Rumah  ...        NaN   
1425     600 m²        200 m²      NaN         Rumah  ...        NaN   

     Kondisi_Perabotan  Jumlah_Lantai      Pemandangan Terjangkau_Internet  \
0       Semi Furnished            2.0  Pemukiman Warga                  Ya   
1                  NaN            1.0              NaN                  Ya   
2       Semi Furnished            1.0              NaN                  Ya   
3          Unfurnished            1.0              NaN               Tidak   
4          Unfurnished            2.0  Pemukiman Warga                  Ya   
...                ...            ...              ...                 ...   
1421       Unfurnished            1.0  Pemukiman Warga                  Ya   
1422               NaN            NaN              NaN                 NaN   
1423       Unfurnished            1.0  Pemukiman Warga                  Ya   
1424               NaN            NaN              NaN                 NaN   
1425       Unfurnished            1.0              NaN                 NaN   

     Lebar Jalan     Sumber Air   Hook Kondisi Properti Tipe Iklan  
0        2 Mobil  PAM atau PDAM  Tidak            Bagus     Dijual  
1            NaN  PAM atau PDAM  Tidak            Bagus     Dijual  
2            NaN  PAM atau PDAM  Tidak            Bagus     Dijual  
3            NaN            NaN  Tidak            Bagus     Dijual  
4            NaN      Sumur Bor  

In [11]:
df.isna().sum()

Unnamed: 0                0
Judul                     0
Harga                     0
Lokasi                    0
Kamar_Tidur              51
Kamar_Mandi              52
Luas_Tanah                0
Luas_Bangunan             0
Carport                1169
Tipe_Properti             0
Sertifikat                1
Daya_Listrik             51
Kamar_Pembantu         1184
Dapur                  1195
Ruang_Makan             721
Ruang_Tamu              719
Kondisi_Perabotan      1035
Jumlah_Lantai          1021
Pemandangan            1087
Terjangkau_Internet     720
Lebar Jalan            1099
Sumber Air             1091
Hook                    720
Kondisi Properti        925
Tipe Iklan                0
dtype: int64

In [14]:
df['Kamar_Tidur'].unique()

array([ 5.,  3.,  2.,  6., 12.,  4., 10., nan, 42.,  8., 15.,  7.,  1.,
        9., 11., 28., 24., 32., 29., 17., 13., 14., 99., 25.])

In [16]:
df['Kamar_Mandi'].unique()

array([  3.,   2.,   4.,   1.,  10.,   6.,  nan,  45.,  15.,   9.,   7.,
         8.,   5.,  13.,  29.,  11., 120.,  12.,  14.,  99.,  25.])

In [17]:
df['Carport'].unique()

array([ 1.,  3., nan,  2.,  5.,  4., 10.,  6.])

In [18]:
df['Sertifikat'].unique()

array(['SHM - Sertifikat Hak Milik', 'HGB - Hak Guna Bangunan',
       'Lainnya (PPJB,Girik,Adat,dll)', nan], dtype=object)

In [19]:
df['Daya_Listrik'].unique()

array(['4400 Watt', '2200 Watt', '1300 Watt', '5500 Watt', nan,
       '3500 Watt', '33000 Watt', '6600 Watt', '16500 Watt', '7600 Watt',
       '900 Watt', '13200 Watt', '3300 Watt', '12700 Watt', '10000 Watt',
       '10600 Watt', '23000 Watt', '7700 Watt', '13300 Watt',
       '22000 Watt', '13900 Watt', '9500 Watt', '11000 Watt',
       '19000 Watt'], dtype=object)

In [20]:
df['Kamar_Pembantu'].unique()

array([ 1., nan,  3.,  2.,  5., 19.,  4.])

In [21]:
df['Dapur'].unique()

array([ 1., nan,  2., 10.])